# docs: https://docs.flet.dev/publish/#github-actions/

name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:  # Permite ejecutarlo manualmente desde la web de GitHub

env:
  UV_PYTHON: "3.12"
  PYTHONUTF8: 1
  # Desactivar output interactivo (evita EOFError en CI)
  FLET_CLI_NO_RICH_OUTPUT: 1

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Ensure Python packages are recognized
        run: |
          touch ui/__init__.py core/__init__.py

      - name: Build Flet APK
        shell: bash
        run: |
          uv run flet build apk --yes --no-interactive --verbose

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: VisionFlow-Finance-APK
          path: build/apk
          if-no-files-found: warn
